version: "3"

services:
  masterdb:
    platform: linux/amd64
    image: mysql:5.7.34
    ports: 
      - 4407:3306
    environment: 
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_main
    command: --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - default
  allfilm_api:
    image: ramenhoang/allfilm_api
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - "masterdb"
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - default

networks: 
  default: